### ISSUE TITLE
NoSuchTableError: library_old when running mixxx_to_rekordbox_xml.py

### ISSUE THREAD

**Issue by cambrian-dk** [FrankwaP/mixxx-utils#1]
I am getting an error: `sqlalchemy.exc.NoSuchTableError: library_old` when running `mixxx_to_rekordbox_xml.py`. Is this related to [this issue](https://github.com/mixxxdj/mixxx/issues/12328) and is there a fix? running [mixxxdb_cleanup.sql](https://github.com/mixxxdj/mixxx/blob/main/tools/mixxxdb_cleanup.sql) doesn't seem to help.

Thanks! :)

**Comment by FrankwaP** [comment]
Hi  :-)  
Thanks for raising this problem!

You're right, now I remember that I had to fix the database so my scripts work!

I've modified the [README.md](https://github.com/FrankwaP/mixxx-utils/blob/main/README.md) so it's now explicit.  
And I've added explanations on how to do it in [fix_mixxx_db.md](https://github.com/FrankwaP/mixxx-utils/blob/main/fix_mixxx_db.md).

I think we can consider this fixed?

**Comment by cambrian-dk** [comment]
Hey, yup! Works and verified. :) Would maybe add a small comment to the [fix_mixxx_db.md](https://github.com/FrankwaP/mixxx-utils/blob/main/fix_mixxx_db.md) to disable the `Foreign Keys` Pragma before modifying the table (for me, it was turned on by default). Thanks for your help!

**Comment by FrankwaP** [comment]
Good catch!  
I've added your recommendation to the [fix_mixxx_db.md](https://github.com/FrankwaP/mixxx-utils/blob/main/fix_mixxx_db.md) file.

Have a nice day!
